[tool.poetry]
name = "histafrica-backend"
version = "0.1.0"
description = ""
authors = ["jose.tandavala <jose.tandavala@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
safety = "^3.2.6"
bandit = "^1.7.9"
flake8 = "^7.1.1"
isort = "^5.13.2"
black = "^24.8.0"
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
